url: https://github.com/davidsosavaldes/Attire
issues: https://github.com/davidsosavaldes/Attire/issues
releases: https://github.com/davidsosavaldes/Attire/wiki/Release-Notes
motto: "Attire is an implementation of a template engine combined with an asset management framework for CodeIgniter 3.0."
version: 2.0.1
demo:
  url: "https://www.youtube-nocookie.com/embed/SwAzluknlNI?rel=0&amp;showinfo=0&amp;hd=1"
  description: Fronted arquitecture in less of 2 minutes.